namespace Binah.Webhooks.Templates;

/// <summary>
/// Markdown templates for pull request descriptions
/// </summary>
public static class PullRequestTemplates
{
    /// <summary>
    /// Template for ontology refactoring pull requests
    /// </summary>
    public static string OntologyRefactoring(
        string entityName,
        int addedProperties,
        int updatedRelationships,
        int refactoredValidators,
        List<string> files)
    {
        return $@"## Summary

AI-generated ontology refactoring for **{entityName}** entity.

This pull request was automatically created by the **Binah.Regen** service based on ontology schema changes.

## Changes

- ✅ Added {addedProperties} new properties
- ✅ Updated {updatedRelationships} relationships
- ✅ Refactored {refactoredValidators} validators

## Modified Files

{string.Join("\n", files.Select(f => $"- `{f}`"))}

## Schema Validation

- [ ] Schema validation passes
- [ ] Generated code compiles
- [ ] Unit tests pass
- [ ] Integration tests pass

## Testing Checklist

- [ ] Verify entity CRUD operations
- [ ] Test relationship traversal
- [ ] Validate data constraints
- [ ] Check backward compatibility

## Deployment Notes

- This PR modifies the core ontology schema
- Review migration scripts before merging
- Coordinate deployment with downstream services
- Notify affected teams

## Auto-Generated

This pull request was created automatically by **Binah.Regen** service.
- Ontology version: {DateTime.UtcNow:yyyy-MM-dd}
- Generated at: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss UTC}

---

**⚠️ Important:** Review all changes carefully before merging. While this PR was auto-generated, manual review is required for production deployments.
";
    }

    /// <summary>
    /// Template for code generation pull requests
    /// </summary>
    public static string CodeGeneration(
        string generatedComponent,
        List<string> files,
        string? additionalNotes = null)
    {
        return $@"## Summary

AI-generated code for **{generatedComponent}**.

This pull request contains code automatically generated by the **Binah.Regen** service.

## Generated Files

{string.Join("\n", files.Select(f => $"- `{f}`"))}

Total files: {files.Count}

## Code Quality Checks

- [ ] Code compiles without errors
- [ ] No compiler warnings
- [ ] Code follows project conventions
- [ ] All generated tests pass

## Review Checklist

- [ ] Verify generated code matches specification
- [ ] Check for proper error handling
- [ ] Validate dependency injection setup
- [ ] Review logging statements
- [ ] Confirm API endpoints follow REST conventions

## Testing

```bash
# Build the project
dotnet build

# Run unit tests
dotnet test

# Run integration tests (if applicable)
dotnet test --filter Category=Integration
```

## Additional Notes

{additionalNotes ?? "No additional notes."}

## Auto-Generated

This pull request was created automatically by **Binah.Regen** service.
- Generated at: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss UTC}

---

**⚠️ Important:** This is auto-generated code. Please review thoroughly before merging to ensure it meets your requirements.
";
    }

    /// <summary>
    /// Template for bug fix pull requests
    /// </summary>
    public static string BugFix(
        string bugDescription,
        string fixDescription,
        List<string> files,
        string? issueNumber = null)
    {
        var issueRef = !string.IsNullOrEmpty(issueNumber) ? $"Fixes #{issueNumber}" : "";

        return $@"## Bug Description

{bugDescription}

{issueRef}

## Fix Applied

{fixDescription}

## Changes Made

{string.Join("\n", files.Select(f => $"- `{f}`"))}

## Testing

- [ ] Bug is reproducible before fix
- [ ] Bug is resolved after fix
- [ ] No regressions introduced
- [ ] Unit tests added for bug scenario
- [ ] Integration tests pass

## Verification Steps

1. Reproduce the original bug
2. Apply the fix
3. Verify the bug no longer occurs
4. Run full test suite
5. Check for any side effects

## Risk Assessment

- **Risk Level:** Low/Medium/High
- **Affected Areas:** [List affected components]
- **Rollback Plan:** [Describe rollback strategy]

---

**Auto-Generated** by Binah.Regen service at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss UTC}
";
    }

    /// <summary>
    /// Template for feature addition pull requests
    /// </summary>
    public static string FeatureAddition(
        string featureName,
        string featureDescription,
        List<string> files,
        List<string> apiEndpoints,
        bool requiresDatabaseMigration)
    {
        var migrationWarning = requiresDatabaseMigration
            ? "\n⚠️ **This feature requires database migration**\n"
            : "";

        return $@"## Feature

**{featureName}**

{featureDescription}

{migrationWarning}

## New Components

{string.Join("\n", files.Select(f => $"- `{f}`"))}

## API Endpoints

{(apiEndpoints.Any() ? string.Join("\n", apiEndpoints.Select(e => $"- `{e}`")) : "No new API endpoints")}

## Implementation Checklist

- [ ] Feature implemented according to spec
- [ ] API endpoints documented
- [ ] Unit tests added
- [ ] Integration tests added
- [ ] Swagger documentation updated
- [ ] Database migrations created (if needed)
- [ ] Error handling implemented
- [ ] Logging added

## Testing

```bash
# Build
dotnet build

# Run tests
dotnet test

# Test API endpoints
curl http://localhost:8098/api/...
```

## Documentation

- [ ] API documentation updated
- [ ] README updated (if needed)
- [ ] Usage examples added
- [ ] Architecture diagrams updated (if needed)

## Deployment

{(requiresDatabaseMigration ? "- [ ] Run database migrations before deployment\n" : "")}
- [ ] Update environment variables (if needed)
- [ ] Notify DevOps team
- [ ] Update deployment checklist

---

**Auto-Generated** by Binah.Regen service at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss UTC}
";
    }

    /// <summary>
    /// Template for refactoring pull requests
    /// </summary>
    public static string Refactoring(
        string refactoringScope,
        string refactoringReason,
        List<string> files,
        bool breakingChanges)
    {
        var breakingWarning = breakingChanges
            ? "\n⚠️ **WARNING: This refactoring contains breaking changes**\n"
            : "";

        return $@"## Refactoring Scope

{refactoringScope}

{breakingWarning}

## Reason for Refactoring

{refactoringReason}

## Modified Files

{string.Join("\n", files.Select(f => $"- `{f}`"))}

Total files modified: {files.Count}

## Changes Made

- [ ] Code structure improved
- [ ] Performance optimized
- [ ] Code duplication removed
- [ ] Design patterns applied
- [ ] Dependencies cleaned up

## Quality Metrics

- [ ] All tests pass
- [ ] Code coverage maintained or improved
- [ ] No new compiler warnings
- [ ] Static analysis passes

## Backward Compatibility

{(breakingChanges
    ? "⚠️ This refactoring introduces breaking changes. Migration guide required."
    : "✅ This refactoring maintains backward compatibility.")}

## Testing Strategy

- [ ] Existing tests pass without modification
- [ ] Integration tests verify behavior unchanged
- [ ] Performance benchmarks show improvement or no regression

---

**Auto-Generated** by Binah.Regen service at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss UTC}
";
    }

    /// <summary>
    /// Simple template for general pull requests
    /// </summary>
    public static string General(
        string title,
        string description,
        List<string> files)
    {
        return $@"## {title}

{description}

## Files Changed

{string.Join("\n", files.Select(f => $"- `{f}`"))}

Total files: {files.Count}

## Testing

- [ ] Code compiles
- [ ] Tests pass
- [ ] Manual testing completed

## Review Checklist

- [ ] Code follows project conventions
- [ ] Documentation updated
- [ ] No obvious bugs or security issues

---

**Auto-Generated** by Binah.Regen service at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss UTC}
";
    }
}
